# Generated by Django 3.2.3 on 2021-10-31 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1200)),
            ],
            options={
                'verbose_name_plural': 'marketpostcategory',
            },
        ),
        migrations.CreateModel(
            name='SellerMarketPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.CharField(default='100', max_length=200)),
                ('telephone_number', models.CharField(default='08000000000', max_length=200)),
                ('picture1', models.URLField(blank=True, default='default.jpg', null=True)),
                ('picture2', models.URLField(blank=True, default='default.jpg', null=True)),
                ('picture3', models.URLField(blank=True, default='default.jpg', null=True)),
                ('picture4', models.URLField(blank=True, default='default.jpg', null=True)),
                ('picture5', models.URLField(blank=True, default='default.jpg', null=True)),
                ('slug', models.SlugField(default='', max_length=200)),
                ('sellcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sellcategorymenu', to='market.marketpostcategory')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SellerMarketPost',
            },
        ),
    ]
