# Generated by Django 3.2.3 on 2021-07-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeshopuser',
            name='telephone',
            field=models.CharField(default='080', max_length=150),
        ),
        migrations.AddField(
            model_name='freeshopuser',
            name='verify_email',
            field=models.CharField(default='shopuser@gmail.com', max_length=150),
        ),
    ]
