# Generated by Django 3.2.3 on 2021-07-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_auto_20210716_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeshopuser',
            name='address',
            field=models.CharField(default='nigeria', max_length=150),
        ),
    ]
