# Generated by Django 3.2.3 on 2021-07-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_freeshopuser_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeShopUser',
        ),
    ]
