# Generated by Django 3.2.3 on 2021-08-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0013_rename_profile_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'userprofile'},
        ),
    ]
