"""
Django settings for freeshop project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import environ
from django.contrib.messages import constants as messages
import django_heroku # new line (heroku)


# INITIALIZE ENVIRONMENT VARIABLES
env = environ.Env()

# READING .env FILE
environ.Env.read_env()




# messages alert tags and css styling
MESSAGE_TAGS = {
        messages.DEBUG: 'alert-secondary py-3',
        messages.INFO: 'alert-info py-3',
        messages.SUCCESS: 'alert-success py-3',
        messages.WARNING: 'alert-warning py-3',
        messages.ERROR: 'alert-danger py-3',       
}





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATE_DIR_1 = BASE_DIR / 'market/templates'           # TEMPLATES DIRECTORY FOR FIRST APP
TEMPLATE_DIR_2 = BASE_DIR / 'visitor/templates'          # TEMPLATES DIRECTORY FOR SECOND APP


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['freeshopnija.herokuapp.com', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'visitor',
    'market',
    'crispy_forms',
    'django_bootstrap_breadcrumbs',
    'django.contrib.humanize',       # for adding "human touch" to templates
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',           # new line (heroku)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'freeshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR_1, TEMPLATE_DIR_2,],              # TEMPLATES DIRECTORIES DEFINED
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'freeshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env("DATABASE_NAME"),                   # database name
        'USER': env("DATABASE_USER"),                   # database user
        'PASSWORD': env("DATABASE_PASSWORD"),           # database password
        'HOST': '127.0.0.1',                            # database host
        'PORT': '5432',                                 # database port
    }
}






# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

# PASSWORD HASHERS ORDER OF PRIORITY
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 9,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# new line (heroku)
# --------------------------------------------------------
STATIC_URL = '/static/'                         

STATICFILES_DIRS = [BASE_DIR / 'static']       

STATIC_ROOT = BASE_DIR / 'static_root'       

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' 



# DEFINING THE MEDIA FILES URL
MEDIA_URL = '/media/'


# DEFINING THE MEDIA FILES LOCATION
MEDIA_ROOT = BASE_DIR / 'media'





# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# DEFINING THE BOOTSTRAP FOR CRISPY-FORMS
CRISPY_TEMPLATE_PACK = 'bootstrap4'



# DEFINE THE LOGIN URL FOR PAGES WITH "@login_required" SET ON THEM
# IF THE USER IS NOT LOGGED IN, REDIRECT THE USER HERE
LOGIN_URL = 'freeshop_login_to_continue'        




# DEFINE MAIL SETTINGS
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False       # just added
DEFAULT_FROM_EMAIL = 'Freeshop Team <noreply@freeshop.com>'
EMAIL_HOST_USER = env("EMAIL_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_PASSWORD")



# new line (heroku)
# --------------------------------------------------------
import dj_database_url 
prod_db  =  dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(prod_db)



# new line (heroku)
# --------------------------------------------------------
django_heroku.settings(locals())    # new line




